import { Injectable } from '@nestjs/common';
import {
  AiSummaryContext,
  AiSummaryProvider,
  AiSummaryResult,
} from '../ai-summary.provider';

const ACTIVITY_PHRASES = [
  'steady momentum',
  'good cadence',
  'solid collaboration',
  'active engagement',
];

@Injectable()
export class MockAiSummaryProvider implements AiSummaryProvider {
  readonly name = 'mock';

  async generate(context: AiSummaryContext): Promise<AiSummaryResult> {
    await new Promise((resolve) => setTimeout(resolve, 1100));

    const { project, milestones, announcements, recentMessages } = context;
    const inProgress = milestones.filter((m) => m.status === 'in_progress');
    const planned = milestones.filter((m) => m.status === 'planned');
    const delayed = milestones.filter((m) => m.status === 'delayed');
    const completed = milestones.filter((m) => m.status === 'completed');

    const latest = recentMessages[0];
    const activityPhrase =
      ACTIVITY_PHRASES[recentMessages.length % ACTIVITY_PHRASES.length];

    const overviewParts = [
      `"${project.name}" is a project with ${context.memberCount} member${context.memberCount === 1 ? '' : 's'}.`,
    ];
    if (project.description) {
      overviewParts.push(`Scope: ${project.description}`);
    }
    if (milestones.length > 0) {
      overviewParts.push(
        `${inProgress.length} milestone${inProgress.length === 1 ? '' : 's'} in progress, ${planned.length} planned, ${completed.length} completed${delayed.length ? ` and ${delayed.length} delayed` : ''}.`,
      );
    }
    if (recentMessages.length > 0) {
      overviewParts.push(
        `The team has shown ${activityPhrase} with ${recentMessages.length} message${recentMessages.length === 1 ? '' : 's'} in recent activity.`,
      );
    }
    overviewParts.push(
      'This summary is generated by the mock AI provider and is intended for demonstration.',
    );

    const keyDecisions = announcements.length
      ? announcements.slice(0, 3).map((a) => a.title)
      : ['No formal announcements have been made yet.'];

    const actionItems = milestones
      .filter((m) => m.status === 'in_progress' || m.status === 'planned')
      .slice(0, 5)
      .map(
        (m) =>
          `Drive "${m.title}" to completion (currently ${m.progress}% complete).`,
      );
    if (actionItems.length === 0) {
      actionItems.push('Define the next set of project milestones.');
    }

    const blockers = delayed.map(
      (m) => `Milestone "${m.title}" is delayed and needs attention.`,
    );
    if (blockers.length === 0 && latest) {
      blockers.push(
        `No blocking issues detected. Most recent message from ${latest.user}: "${latest.text.slice(0, 120)}".`,
      );
    }
    if (blockers.length === 0) {
      blockers.push('No blocking issues detected.');
    }

    return {
      overview: overviewParts.join(' '),
      keyDecisions,
      actionItems,
      blockers,
      generatedAt: new Date().toISOString(),
      provider: this.name,
    };
  }
}
