import { Injectable } from '@nestjs/common';
import {
  ConversationSummaryContext,
  ConversationSummaryProvider,
  ConversationSummaryResult,
} from '../conversation-summary.provider';

const ACTIVITY_PHRASES = [
  'steady momentum',
  'active discussion',
  'productive collaboration',
  'healthy cadence',
  'focused engagement',
];

const DECISION_HINTS = [
  'decision',
  'decided',
  'agreed',
  'confirmed',
  'approved',
  'finalized',
  'we will',
  'going with',
  'settled on',
];

const ACTION_HINTS = [
  'will do',
  'need to',
  'should',
  'must',
  'action',
  'todo',
  'to-do',
  'follow up',
  'send',
  'schedule',
  'share',
  'create',
  'draft',
  'fix',
  'let me',
  'i will',
  "i'll",
];

const QUESTION_HINTS = [
  '?',
  'unresolved',
  'open question',
  'not sure',
  'waiting on',
  'blocked',
  'pending',
  'tbd',
  'to be decided',
];

function hasAny(text: string, hints: string[]): boolean {
  const lower = text.toLowerCase();
  return hints.some((hint) => lower.includes(hint));
}

@Injectable()
export class MockConversationSummaryProvider implements ConversationSummaryProvider {
  readonly name = 'mock';

  async generate(
    context: ConversationSummaryContext,
  ): Promise<ConversationSummaryResult> {
    await new Promise((resolve) => setTimeout(resolve, 900));

    const { channelName, periodType, messages } = context;

    const periodLabel =
      periodType === 'daily'
        ? 'today'
        : periodType === 'weekly'
          ? 'this week'
          : 'this conversation';

    const overviewParts = [
      channelName
        ? `"${channelName}" had ${messages.length} message${messages.length === 1 ? '' : 's'} in ${periodLabel}.`
        : `This conversation had ${messages.length} message${messages.length === 1 ? '' : 's'} in ${periodLabel}.`,
    ];

    const participants = new Set(messages.map((m) => m.user));
    if (participants.size > 0) {
      overviewParts.push(
        `${participants.size} participant${participants.size === 1 ? '' : 's'} joined the discussion.`,
      );
    }

    const activityPhrase =
      ACTIVITY_PHRASES[messages.length % ACTIVITY_PHRASES.length];
    if (messages.length > 0) {
      overviewParts.push(`The team showed ${activityPhrase}.`);
    }
    overviewParts.push(
      'This summary is generated by the mock AI provider and is intended for demonstration.',
    );

    const keyDecisions = messages
      .filter((m) => hasAny(m.text, DECISION_HINTS))
      .slice(0, 3)
      .map((m) => this.shorten(m.text));

    const actionItems = messages
      .filter((m) => hasAny(m.text, ACTION_HINTS))
      .slice(0, 5)
      .map((m) => `"${this.shorten(m.text)}"`);

    const unresolvedTopics = messages
      .filter((m) => hasAny(m.text, QUESTION_HINTS))
      .slice(0, 4)
      .map((m) => this.shorten(m.text));

    if (keyDecisions.length === 0) {
      keyDecisions.push('No explicit decisions were recorded in this period.');
    }
    if (actionItems.length === 0) {
      actionItems.push('No action items were explicitly called out.');
    }
    if (unresolvedTopics.length === 0) {
      unresolvedTopics.push('No open questions or blockers were flagged.');
    }

    return {
      overview: overviewParts.join(' '),
      keyDecisions,
      actionItems,
      unresolvedTopics,
      generatedAt: new Date().toISOString(),
      provider: this.name,
    };
  }

  private shorten(text: string): string {
    return text.slice(0, 160) || '(no text)';
  }
}
